// organize imports in alphabet order to sparse the conflict when adding a new chain
import {
  Localhost,
  Hardhat,
  Avalanche,
  BSC,
  BSCTestnet,
  Fantom,
  FantomTestnet,
  Harmony,
  Mainnet,
  Ropsten,
  Rinkeby,
  Goerli,
  Kovan,
  Moonriver,
  MoonbaseAlpha,
  Palm,
  Polygon,
  Mumbai,
  Songbird,
  Theta,
  ThetaTestnet,
  xDai,
} from '../model'

// rough alphabet order (put network from the same chain together)
export const DEFAULT_SUPPORTED_CHAINS = [
  Localhost,
  Hardhat,
  Avalanche,
  Mainnet,
  Ropsten,
  Rinkeby,
  Goerli,
  Kovan,
  BSC,
  BSCTestnet,
  Fantom,
  FantomTestnet,
  Harmony,
  Moonriver,
  MoonbaseAlpha,
  Palm,
  Polygon,
  Mumbai,
  Songbird,
  Theta,
  ThetaTestnet,
  xDai,
]

export enum ChainId {
  Mainnet = 1,
  Ropsten = 3,
  Rinkeby = 4,
  Goerli = 5,
  Kovan = 42,
  BSC = 56,
  BSCTestnet = 97,
  xDai = 100,
  Polygon = 137,
  Theta = 361,
  ThetaTestnet = 365,
  Moonriver = 1285,
  Mumbai = 80001,
  Harmony = 1666600000,
  Palm = 11297108109,
  Localhost = 1337,
  Hardhat = 31337,
  Fantom = 250,
  FantomTestnet = 4002, 
  Avalanche = 43114,
  Songbird = 19,
  MoonbaseAlpha = 1287,
}
