// NOTE: We explicitly export the symbols in the root index.ts file to have better control over package's public API.

export {
  ChainId,
  BNB,
  BUSD,
  Chain,
  Config,
  DEFAULT_SUPPORTED_CHAINS,
  Dai,
  ERC20,
  ERC20Interface,
  ERC20Mock,
  ERC20MockInterface,
  Ether,
  FullConfig,
  KovanDai,
  KovanEther,
  MultiCall,
  MultiCall2,
  MultiCall2ABI,
  MultiCallABI,
  MulticallAddresses,
  NATIVE_CURRENCY,
  NodeUrls,
  TestBNB,
  TestBUSD,
} from './constants'
export {
  DAppProvider,
  DAppProviderProps,
  AddNotificationPayload,
  RemoveNotificationPayload,
  ChainState,
  Notification,
  Notifications,
  RawCall,
  RawCallResult,
  State,
  StoredTransaction,
  StoredTransactions,
  getStoredTransactionState,
  multicall,
  multicall2,
  useBlockNumber,
  useConfig,
  useNetwork,
  useUpdateConfig,
  // To be removed from public API:
  ChainCall,
  SingleChainState,
  Network,
  NetworkActivator,
  NetworkProvider,
  BlockNumberProvider,
  Action,
  BlockNumberChanged,
  BlockNumberContext,
  ChainStateAction,
  ConfigContext,
  ConfigProvider,
  MultiChainState,
  MultiChainStateProvider,
  MultiChainStatesContext,
  blockNumberReducer,
  callsReducer,
  chainStateReducer,
  DEFAULT_NOTIFICATIONS,
  DEFAULT_STORED_TRANSACTIONS,
  useMultiChainStates,
  useTransactionsContext,
  useNotificationsContext,
} from './providers'
export {
  Call,
  ContractCall,
  Web3Ethers,
  useBlockMeta,
  useCall,
  useCalls,
  useChainMeta,
  useContractFunction,
  useEtherBalance,
  useEthers,
  useGasPrice,
  useLookupAddress,
  useMulticallAddress,
  useNotifications,
  useSendTransaction,
  useToken,
  useTokenAllowance,
  useTokenBalance,
  useTokenList,
  TokenList,
  useTransactions,
  // To be removed from public API:
  useContractCall,
  useContractCalls,
  useChainCall,
  useChainCalls,
  useChainState,
  connectContractToSigner,
  useDebounce,
  useLocalStorage,
  useDebouncePair,
  useInterval,
} from './hooks'
export {
  Currency,
  CurrencyValue,
  FiatCurrency,
  NativeCurrency,
  Token,
  TransactionOptions,
  TransactionState,
  TransactionStatus,
  transactionErrored,
} from './model'
export * from './model/chain'
export {
  CallResult,
  addressEqual,
  compareAddress,
  shortenAddress,
  shortenIfAddress,
  shortenIfTransactionHash,
  shortenTransactionHash,
  // To be removed from public API:
  warnOnInvalidCall,
  getChainById,
  encodeCallData,
  decodeCallResult,
  getChainMeta,
  isLocalChain,
  isTestChain,
  getChainName,
  getUniqueCalls,
  getExplorerAddressLink,
  getExplorerTransactionLink,
} from './helpers'
